ZK-4771: Provide a way to add theme-uri without extends any existing …
zkoss/atlantic pull request #191
Opened 2021-03-15 08:21 UTC by plijyfes

…ThemeProvider

2021-03-17 03:12 UTC, scribetw requested changes

2021-03-17 03:12 UTC, scribetw commented on src/org/zkoss/theme/atlantic/AtlanticPEThemeProvider.java
> +@Deprecated
remains an empty class implementation

2021-03-17 03:12 UTC, scribetw commented on pom.xml
> +		<zk.version>9.6.0-SNAPSHOT</zk.version>
wait for FL

2021-03-25 06:54 UTC, DevChu approved these changes

2021-03-25 07:11 UTC, scribetw approved these changes

2021-03-25 07:11 UTC, merged